### ISSUE TITLE
关于绘图方式改进

### ISSUE THREAD

**Issue by xen0n** [yueyoum/renren-relationship#1]
现在程序可以搞出节点和边，何不试试导出dot格式，拿Graphviz绘图。。

**Comment by yueyoum** [comment]
@xen0n  
OK， thanks, 我明天试试

**Comment by reverland** [comment]
记的networkx可以直接用graphviz绘图。不过nx画的有什么不好吗？速度稍微慢点？

**Comment by yueyoum** [comment]
我昨晚试了下， 是 networkx 可以输出 graphviz 的 dot格式，然后用 graphviz 来绘图

昨晚先试的是 pygraphviz， 发现这货绘图好慢，果断放弃了

**Comment by yueyoum** [comment]
@xen0n  @reverland 

已经改用  graphviz ， 看 README 里就有生成的图片

没用 pygraphviz， 直接 用的 nx.write_dot 来导出 dot文件， 然后再绘图的
