### ISSUE TITLE
人人API？

### ISSUE THREAD

**Issue by reverland** [yueyoum/renren-relationship#2]
有没有考虑过用人人开放平台api？好像可以直接获取json或xml格式的好友列表。也许省去漫无天日的抓好友时间(相信并行会比我想象的快多了……)

**Comment by yueyoum** [comment]
@reverland 

我看过 renren api， 不能满足要求， API 只能获取授权用户自己的好友， 然后就完了

我还要获取好友的好友。

并且使用时，还要让其他人授权，太麻烦。

其实如果只是快速的获取自身好友列表， 校内XMPP就可以做到。 整个过程也就几秒
