### ISSUE TITLE
question

### ISSUE THREAD

**Issue by xptree** [yueyoum/renren-relationship#4]
I can get the result.png,but also get "Exception KeyError: KeyError(17784656,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored"...and I have no idea about it.

**Comment by yueyoum** [comment]
Don't worry about it.

It seems like some library are not **thread safe** .

One thread delete a key from a dict,  and another thread then play this dict with the deleted key.
So, the KeyError Exception raised.

Just ignore it.   :-)
